version: "3.9"

services:
  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - product-service
      - order-service
      - inventory-service
      - payment-service

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  ### USER
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8001:8000"
    depends_on:
      - user-db
    environment:
      DB_NAME: user_db
      DB_USER: user
      DB_PASSWORD: user
      DB_HOST: user-db
      DB_PORT: 5432

  user-db:
    image: postgres:15
    container_name: user-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user

  ### PRODUCT
  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "8002:8000"
    depends_on:
      - product-db
    environment:
      DB_NAME: product_db
      DB_USER: product
      DB_PASSWORD: product
      DB_HOST: product-db
      DB_PORT: 5432

  product-db:
    image: postgres:15
    container_name: product-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product

  ### ORDER
  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "8003:8000"
    depends_on:
      - order-db
      - rabbitmq
    environment:
      DB_NAME: order_db
      DB_USER: order
      DB_PASSWORD: order
      DB_HOST: order-db
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  order-db:
    image: postgres:15
    container_name: order-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order

  order-consumer:
    build: ./services/order-service
    container_name: order-consumer
    command: ["python", "manage.py", "consume_order_events"]
    depends_on:
      - order-db
      - rabbitmq
    environment:
      DB_NAME: order_db
      DB_USER: order
      DB_PASSWORD: order
      DB_HOST: order-db
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  ### INVENTORY
  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    ports:
      - "8004:8000"
    depends_on:
      - inventory-db
      - rabbitmq
    environment:
      DB_NAME: inventory_db
      DB_USER: inventory
      DB_PASSWORD: inventory
      DB_HOST: inventory-db
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  inventory-db:
    image: postgres:15
    container_name: inventory-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory

  inventory-consumer:
    build: ./services/inventory-service
    container_name: inventory-consumer
    command: ["python", "manage.py", "consume_order_events"]
    depends_on:
      - inventory-db
      - rabbitmq
    environment:
      DB_NAME: inventory_db
      DB_USER: inventory
      DB_PASSWORD: inventory
      DB_HOST: inventory-db
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  ### PAYMENT
  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "8005:8000"
    depends_on:
      - payment-db
      - rabbitmq
    environment:
      DB_NAME: payment_db
      DB_USER: payment
      DB_PASSWORD: payment
      DB_HOST: payment-db
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  payment-db:
    image: postgres:15
    container_name: payment-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment

  payment-consumer:
    build: ./services/payment-service
    container_name: payment-consumer
    command: ["python", "manage.py", "consume_order_events"]
    depends_on:
      - payment-db
      - rabbitmq
    environment:
      DB_NAME: payment_db
      DB_USER: payment
      DB_PASSWORD: payment
      DB_HOST: payment-db
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
